baseurl:     /alix
safe: false
permalink: /posts/:title.html
markdown:    kramdown
rdiscount:   { extensions: [smart] }
exclude:
  - README.md

name: Alix的技术博客
host: localhost
desc: 不会炒菜的程序员不是好QA!

custom:
    category:
        default: 默认分类
        develop: 日常开发
    categories:
      - name:  default
        title: 默认分类

      - name:  develop
        title: 日常开发

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Alix
        email: chyun.wu@gmail.com
        disqus:     /alix          # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: chyun                 # GitHub账号
        gravatar: 6d141df40950583e6a1f3e73506a8292  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
